"use client";

import { useCallback, useEffect, useState } from "react";
import { ArrowLeft, ArrowRight, BrainCircuit, Check, Globe2, Headphones, Menu, Pause, Play, Sparkles, Waves, X } from "lucide-react";

const slides = ["The promise", "The loop", "Live scrape", "The system"];

function Eyebrow({ number, children }: { number: string; children: React.ReactNode }) {
  return <p className="eyebrow"><span>{number}</span><i />{children}</p>;
}

function SlideOne() {
  return <section className="slide slide-one" aria-labelledby="slide-one-title">
    <div className="sky-glow" /><div className="wave-field" aria-hidden="true"><span /><span /><span /></div>
    <div className="slide-content hero-content"><Eyebrow number="01 / 04">A local voice interface</Eyebrow><div className="hero-layout"><div><p className="kicker"><span className="live-ping" /> BUILT FOR THE MOMENT BETWEEN ASKING AND KNOWING</p><h1 id="slide-one-title">Let the web<br /><em>speak clearly.</em></h1><p className="hero-copy">Amari is a conversational layer for the open web. Ask a question out loud, let a local model investigate, and hear the useful part back.</p><div className="hero-route"><span className="route-chip"><Headphones size={15} /> voice in</span><b>→</b><span className="route-chip"><Globe2 size={15} /> web context</span><b>→</b><span className="route-chip active"><Sparkles size={15} /> clear answer</span></div></div><div className="hero-art" aria-hidden="true"><div className="sun-disc" /><div className="horizon" /><div className="float-card card-a"><span className="mini-icon"><Headphones size={14} /></span><span><small>YOU ASK</small><b>“What changed?”</b></span></div><div className="float-card card-b"><span className="mini-icon blue"><Globe2 size={14} /></span><span><small>AMARI LOOKS</small><b>3 live sources</b></span></div><div className="answer-card"><div className="answer-top"><span className="status-dot" /> LOCAL ANSWER <span>01.8s</span></div><p>“The useful change is a new launch window on Friday.”</p><div className="answer-line"><span /><span /><span /></div></div></div></div></div><div className="slide-foot"><span>LOCAL MODEL / WEB-AWARE / HUMAN-PACED</span><span>AMARI / 2026</span></div>
  </section>;
}

function SlideTwo() {
  const steps = [{ icon: Headphones, label: "Speak", detail: "Ask naturally. No prompt engineering." }, { icon: Globe2, label: "Browse", detail: "Fetch the page, not a stale summary." }, { icon: BrainCircuit, label: "Ground", detail: "Rank context with a local retrieval pass." }, { icon: Waves, label: "Respond", detail: "Return the answer in a human rhythm." }];
  return <section className="slide slide-two" aria-labelledby="slide-two-title"><div className="slide-content"><Eyebrow number="02 / 04">The interaction loop</Eyebrow><div className="split-heading"><div><h2 id="slide-two-title">Four quiet moves.<br /><em>One fluid moment.</em></h2></div><p className="lede">The magic is not a chatbot waiting behind a text box. It is a small, visible system that keeps the distance between curiosity and clarity short.</p></div><div className="loop-grid">{steps.map(({ icon: Icon, label, detail }, index) => <div className={`loop-card card-${index}`} key={label}><div className="loop-number">0{index + 1}</div><div className="loop-icon"><Icon size={22} /></div><h3>{label}</h3><p>{detail}</p>{index < 3 && <span className="loop-arrow"><ArrowRight size={17} /></span>}</div>)}</div><div className="quote-bar"><span>THE DESIGN PRINCIPLE</span><strong>Make the work visible. Keep the answer light.</strong></div></div></section>;
}

function SlideThree() {
  return <section className="slide slide-three" aria-labelledby="slide-three-title"><div className="slide-content"><Eyebrow number="03 / 04">A live scrape, made legible</Eyebrow><div className="split-heading"><div><h2 id="slide-three-title">A page goes in.<br /><em>A signal comes out.</em></h2></div><p className="lede">Amari gives the local model a focused slice of the live page, then shows the sources it used — so a fast answer still feels earned.</p></div><div className="scrape-stage"><div className="browser-card"><div className="browser-bar"><span className="browser-dots"><i /><i /><i /></span><span className="address"><Globe2 size={13} /> northstarwireless.com / launch</span><span className="secure">SECURE</span></div><div className="browser-page"><div className="page-skeleton wide" /><div className="page-skeleton medium" /><div className="page-skeleton small" /><div className="page-copy"><span>LAUNCH UPDATE</span><strong>New devices arrive Friday.</strong><small>Northstar Wireless · published 2m ago</small></div><div className="scrape-cursor"><Sparkles size={14} /> captured</div></div></div><div className="signal-panel"><div className="signal-head"><span className="status-dot" /> WEB SCRAPE COMPLETE <b>1.1s</b></div><div className="signal-answer"><small>LOCAL MODEL / SYNTHESIS</small><p>“The launch window moved to Friday. Pre-orders open Thursday at 9am.”</p></div><div className="source-list"><div><Check size={14} /><span><b>Launch update</b><small>northstarwireless.com / launch</small></span></div><div><Check size={14} /><span><b>Pre-order policy</b><small>northstarwireless.com / support</small></span></div></div><div className="signal-foot"><span>3 sources</span><span>grounded answer</span></div></div></div></div></section>;
}

function SlideFour({ onRestart }: { onRestart: () => void }) {
  return <section className="slide slide-four" aria-labelledby="slide-four-title"><div className="deep-wave" aria-hidden="true" /><div className="slide-content"><Eyebrow number="04 / 04">The system underneath</Eyebrow><div className="final-layout"><div><p className="kicker light"><span className="live-ping" /> QUIET INFRASTRUCTURE / QUICK PAYOFF</p><h2 id="slide-four-title">Private by default.<br /><em>Useful by design.</em></h2><p className="final-copy">Local inference, focused browsing, and a retrieval layer that gets out of the way. Amari is designed to feel less like software — and more like a good conversation.</p><button className="replay-button" onClick={onRestart}><Play size={15} /> Replay the story</button></div><div className="system-stack"><div className="stack-label">AMARI RUNTIME</div><div className="stack-row"><span className="stack-icon"><Headphones size={17} /></span><span><b>Voice layer</b><small>Browser speech in / speech out</small></span><span className="stack-live">LIVE</span></div><div className="stack-row"><span className="stack-icon"><Globe2 size={17} /></span><span><b>Web tool</b><small>Bounded fetch + readable extraction</small></span><span className="stack-live">READY</span></div><div className="stack-row"><span className="stack-icon"><BrainCircuit size={17} /></span><span><b>Local model</b><small>llama3.1:latest via Ollama</small></span><span className="stack-live">LOCAL</span></div><div className="stack-row"><span className="stack-icon"><Waves size={17} /></span><span><b>Moss retrieval</b><small>Fast context, no wandering</small></span><span className="stack-live">FAST</span></div><div className="stack-bottom"><span>AMARI / 01</span><span>START WITH A QUESTION</span></div></div></div></div><div className="slide-foot light-foot"><span>AN OCEAN OF INFORMATION / A CLEARER SURFACE</span><span>THANK YOU</span></div></section>;
}

export default function Home() {
  const [current, setCurrent] = useState(0);
  const [menuOpen, setMenuOpen] = useState(false);
  const [playing, setPlaying] = useState(false);
  const goTo = useCallback((index: number) => { setCurrent(Math.max(0, Math.min(slides.length - 1, index))); setMenuOpen(false); }, []);
  const next = useCallback(() => goTo(current + 1), [current, goTo]);
  const previous = useCallback(() => goTo(current - 1), [current, goTo]);
  useEffect(() => { const onKey = (event: KeyboardEvent) => { if (["ArrowRight", " ", "PageDown"].includes(event.key)) { event.preventDefault(); next(); } if (["ArrowLeft", "PageUp"].includes(event.key)) { event.preventDefault(); previous(); } if (event.key === "Home") goTo(0); if (event.key === "End") goTo(slides.length - 1); if (event.key === "Escape") setMenuOpen(false); }; window.addEventListener("keydown", onKey); return () => window.removeEventListener("keydown", onKey); }, [goTo, next, previous]);
  useEffect(() => { if (!playing) return; const timer = window.setInterval(() => setCurrent((value) => value >= slides.length - 1 ? 0 : value + 1), 6500); return () => window.clearInterval(timer); }, [playing]);
  return <main className="deck-shell"><header className="deck-nav"><div className="brand"><span className="brand-mark"><Waves size={15} /></span><span>AMARI</span><small>LOCAL INTELLIGENCE</small></div><nav className={`slide-nav ${menuOpen ? "is-open" : ""}`} aria-label="Presentation slides">{slides.map((slide, index) => <button key={slide} onClick={() => goTo(index)} className={index === current ? "is-current" : ""} aria-label={`Go to slide ${index + 1}: ${slide}`} aria-current={index === current ? "step" : undefined}><span>0{index + 1}</span><i /><b>{slide}</b></button>)}</nav><div className="nav-controls"><button className="icon-button play-toggle" onClick={() => setPlaying((value) => !value)} aria-label={playing ? "Pause autoplay" : "Play autoplay"}>{playing ? <Pause size={15} /> : <Play size={15} />}</button><span className="slide-counter">0{current + 1} <small>/ 04</small></span><button className="icon-button mobile-menu" onClick={() => setMenuOpen((open) => !open)} aria-label={menuOpen ? "Close slide menu" : "Open slide menu"} aria-expanded={menuOpen}>{menuOpen ? <X size={17} /> : <Menu size={17} />}</button><button className="icon-button" onClick={previous} disabled={current === 0} aria-label="Previous slide"><ArrowLeft size={17} /></button><button className="icon-button" onClick={next} disabled={current === slides.length - 1} aria-label="Next slide"><ArrowRight size={17} /></button></div></header><div className="progress-track"><span style={{ width: `${((current + 1) / slides.length) * 100}%` }} /></div><div className="slide-viewport" aria-live="polite">{current === 0 && <SlideOne />}{current === 1 && <SlideTwo />}{current === 2 && <SlideThree />}{current === 3 && <SlideFour onRestart={() => goTo(0)} />}</div><div className="bottom-hint"><span><kbd>←</kbd><kbd>→</kbd> navigate</span><span>{playing ? "AUTOPLAY ON" : "SPACE TO ADVANCE"}</span></div></main>;
}
